# Generated by Django 5.1.2 on 2024-10-17 14:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myproject', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Api',
            new_name='Food',
        ),
    ]
